import type { Content } from "./types";

export const en: Content = {
  name: "Abdulloh Abduvohidov",
  firstName: "Abdulloh",
  role: "Project Manager",
  location: "Tashkent, Uzbekistan",
  currently: "Currently — Project Manager at Davrbank",
  heroTitle: "I take IT projects from idea to production",
  heroLead:
    "Project Manager in banking fintech. 3+ years in IT — from frontend development and my own startup to managing integrations of digital banking products.",
  stats: [
    { value: 3, suffix: "+", label: "years in IT" },
    { value: 9, label: "projects in portfolio" },
    { value: 4, label: "teams & companies" },
    { value: 3, label: "payment systems shipped to PROD" },
  ],
  about: [
    "Project Manager with experience in IT projects and startups. 3+ years in IT: from building and launching products to managing full-cycle projects. Completed the IT Project Management program at Yandex Practicum, working on real cases with real clients.",
    "I work in Agile environments: gathering and analysing requirements, planning timelines and resources, managing risks, and setting and tracking team tasks. I use AI tools for analysis, planning and optimising workflows.",
    "I'm looking for projects where I can grow as a Project Manager and deliver measurable value to the business.",
  ],
  process: [
    { title: "Requirements", text: "Gathering and analysing business requirements, interviewing clients and stakeholders." },
    { title: "Documentation", text: "BRD, technical specs, project charter, UML, flowcharts and business process descriptions." },
    { title: "Planning", text: "Sprints, estimates, budget, resources and risk management." },
    { title: "Coordination", text: "Backend, Frontend, DevOps, adjacent departments and external partners." },
    { title: "Launch", text: "Testing, acceptance, production release and post-launch growth." },
  ],
  facts: [
    { label: "City", value: "Tashkent" },
    { label: "Format", value: "Full-time, on-site" },
    { label: "Business trips", value: "Ready" },
    { label: "Languages", value: "UZ · RU · EN" },
  ],
  jobs: [
    {
      id: "davrbank",
      company: "Davrbank",
      url: "https://davrbank.uz/",
      location: "Tashkent",
      role: "Project Manager",
      period: "Mar 2026 — present",
      duration: "",
      current: true,
      badge: "Fintech · Bank",
      summary:
        "Managing development of digital banking products and integrations with internal banking systems and external partners. Full cycle: from business requirements analysis and documentation to development support, testing and production release.",
      responsibilities: [
        "Gathering and analysing business requirements.",
        "Preparing BRDs, technical specifications and project documentation.",
        "Designing UML diagrams, flowcharts and business process descriptions.",
        "Sprint planning, estimation and task tracking.",
        "Coordinating Backend, Frontend, DevOps and adjacent departments.",
        "Risk management and communication with internal and external stakeholders.",
      ],
      tools: ["Jira", "Confluence", "Figma", "Postman", "Swagger", "Miro", "Google Workspace", "Notion", "TickTick"],
      projects: ["momentcard", "pluscard", "history-transactions"],
    },
    {
      id: "yandex-practicum",
      company: "Yandex Practicum",
      role: "Project Manager",
      period: "Jun 2025 — Jan 2026",
      duration: "8 months",
      badge: "Training projects",
      summary:
        "Managed full-cycle IT training projects: from requirements gathering and planning to delivery to the client. Worked with clients, development and design teams; controlled timelines, scope and quality.",
      responsibilities: [],
      tools: ["Agile", "Kanban", "Trello", "GanttPro", "Figma", "Miro", "Google Workspace", "UML", "BPMN", "CustDev"],
      projects: ["vector-motors", "mood-and-food"],
      note: "Briefs, feature lists, estimates, work plans, risk registers, specs, test cases and presentations — available on request.",
    },
    {
      id: "it-park",
      company: "IT Park",
      role: "Frontend Developer",
      period: "Jan 2025 — Dec 2025",
      duration: "1 year",
      badge: "Development",
      summary:
        "National centre for IT business, startups and technology. Built ecosystem web platforms for startups, IT specialists and investors in close collaboration with product and project teams.",
      responsibilities: [
        "Implemented user flows based on client and product team requirements.",
        "Took part in functional requirement discussions, prioritisation and scope estimation.",
        "Built the authentication and user session management system.",
        "Implemented internationalisation (i18n) and responsive UI.",
      ],
      tools: ["Next.js", "TypeScript", "TanStack", "Zod", "Tailwind CSS", "i18n"],
      projects: ["it-park"],
    },
    {
      id: "syncapp",
      company: "SyncApp",
      location: "Tashkent",
      role: "Co-founder / Project Manager",
      period: "Sep 2024 — Jun 2025",
      duration: "10 months",
      badge: "Startup",
      summary:
        "Low-code platform for business process automation. Ran the project and backlog, coordinated development and design, prepared the MVP and investor materials.",
      responsibilities: [
        "Managed the project and backlog in Trello, tracking deadlines and status.",
        "Coordinated development and design teams to ensure steady delivery.",
        "Shaped requirements, prepared the MVP and designed key user flows.",
      ],
      tools: ["Trello", "Figma", "CustDev", "MVP"],
      projects: ["syncapp"],
    },
  ],
  projects: [
    {
      slug: "momentcard",
      name: "MomentCard",
      company: "Davrbank",
      period: "2026",
      role: "Project Manager",
      status: "In PROD",
      tagline: "Instant bank card issuing for Alif Nasiya customers",
      summary:
        "Davrbank × Alif Nasiya integration: a service that issues a bank card to the customer at the moment of checkout. Built the team from scratch, set up processes and took the project to production.",
      tasks: [
        "Prepared project documentation: project charter, UML, flowcharts, Confluence.",
        "Coordinated the launch and controlled development timelines.",
        "Ran meetings with the internal team and partners.",
        "Built the project team from scratch: Backend, Frontend, Team Lead, DevOps.",
        "Set up team collaboration processes.",
        "Initiated an admin panel for API monitoring and integration statistics.",
        "Coordinated optimisation of customer onboarding, account opening and card issuing.",
      ],
      results: [
        "Successfully released the project to production.",
        "Built an effective development team.",
        "Introduced API monitoring to speed up error analysis.",
        "Optimised customer onboarding and card issuing processes.",
        "Ensured the product kept evolving after launch.",
      ],
      tools: ["Jira", "Confluence", "UML", "FlowChart", "Postman", "Swagger"],
      accent: "blue",
      featured: true,
    },
    {
      slug: "history-transactions",
      name: "History Transactions",
      company: "Davrbank",
      period: "2026",
      role: "Project Manager",
      status: "In PROD",
      tagline: "A unified bank transaction history service",
      summary:
        "Transaction history for cards across Uzbekistan's key payment systems in one place — for customers and for administrators.",
      tasks: [
        "Analysed requirements and wrote the technical specification.",
        "Broke down tasks and designed the UI and admin panel.",
        "Built prototypes in Figma.",
        "Organised testing and documented the project.",
      ],
      results: [
        "Humo, Uzcard and UnionPay transactions shipped to PROD.",
        "Delivered a unified transaction history service.",
        "Prepared complete project documentation.",
      ],
      tools: ["Figma", "Jira", "Confluence", "Swagger"],
      accent: "violet",
    },
    {
      slug: "pluscard",
      name: "PlusCard",
      company: "Davrbank",
      period: "2026",
      role: "Project Manager",
      status: "Early stage",
      tagline: "Integrating a corporate card product with banking systems",
      summary:
        "A corporate card product: architecture analysis, process design and preparing the integration with the BPC Connect processing platform.",
      tasks: [
        "Analysed architecture and business processes.",
        "Prepared the BRD and project documentation.",
        "Described identification, account opening and card issuing processes.",
        "Coordinated the BPC Connect integration and testing.",
      ],
      results: [
        "Business processes and integration documentation prepared.",
        "Organised test account opening and Mastercard card issuing.",
      ],
      tools: ["BRD", "BPMN", "Confluence", "BPC Connect"],
      accent: "cyan",
    },
    {
      slug: "syncapp",
      name: "SyncApp",
      company: "SyncApp",
      period: "2024 — 2025",
      role: "Co-founder / Project Manager",
      status: "MVP",
      tagline: "Low-code platform for business process automation",
      summary:
        "My own startup: from idea and requirements to a working MVP with first users, a financial model for an investor and a well-grounded strategic decision.",
      tasks: [
        "Managed the project and backlog in Trello, tracking deadlines and status.",
        "Coordinated development and design teams.",
        "Shaped requirements, prepared the MVP and designed key user flows.",
      ],
      results: [
        "Launched an MVP with working features and first users — business processes automated without developers.",
        "Built a financial model and investor deck — clear unit economics and potential.",
        "Optimised team processes: faster task delivery and better communication.",
        "Closed the project based on MVP results and user feedback — a data-driven strategic decision.",
      ],
      tools: ["Trello", "Figma", "CustDev", "Unit economics"],
      accent: "amber",
    },
    {
      slug: "it-park",
      name: "IT Park Platforms",
      company: "IT Park",
      period: "2025",
      role: "Frontend Developer",
      status: "3 platforms",
      tagline: "Ecosystem web platforms for startups, IT specialists and investors",
      summary:
        "Building products for the national IT business development centre. Experience “on the other side” helps me speak the same language as developers.",
      products: [
        { name: "StartupBase", text: "A platform for startups, investors and partners." },
        { name: "Outsource.gov.uz", text: "Promoting Uzbekistan as an IT outsourcing hub." },
        { name: "IT Park Ventures", text: "Supporting and scaling tech startups." },
      ],
      tasks: [
        "Implemented user flows based on client and product team requirements.",
        "Built the authentication and user session management system.",
        "Created editable user profiles.",
        "Implemented internationalisation (i18n) and responsive UI.",
        "Built a startup map with filtering and geolocation.",
        "Contributed to Government Challenges, jobs and CV modules.",
      ],
      results: [
        "Improved UX through convenient flows and responsive interfaces.",
        "Expanded the audience with multi-language support.",
        "Increased platform reliability with a solid authentication implementation.",
      ],
      tools: ["Next.js", "TypeScript", "TanStack", "Zod", "Tailwind CSS", "i18n"],
      accent: "emerald",
    },
    {
      slug: "vector-motors",
      name: "Vector Motors",
      company: "Yandex Practicum",
      period: "2025",
      role: "Project Manager",
      status: "Training case",
      tagline: "A full-cycle project with a real client",
      summary:
        "From client interviews to acceptance: requirements, specs, an interactive prototype, plan, budget, risks and testing.",
      tasks: [
        "Interviewed the client, defined goals, requirements and priorities.",
        "Wrote business requirements and a multi-level technical specification.",
        "Built an interactive product prototype in Figma.",
        "Planned project stages, timeline, budget and risks.",
        "Organised the team, set and tracked tasks in Trello.",
        "Prepared test design, test cases, bug reports and feature requests.",
      ],
      results: [
        "Reduced rework thanks to an agreed prototype and requirements.",
        "Ensured transparent task progress and on-time delivery.",
        "Improved product quality through systematic testing and acceptance control.",
      ],
      tools: ["Figma", "Trello", "GanttPro", "Test Design"],
      accent: "rose",
    },
    {
      slug: "mood-and-food",
      name: "Mood & Food",
      company: "Yandex Practicum",
      period: "2025",
      role: "Project Manager",
      status: "Training case",
      tagline: "From brief to project charter and client presentation",
      summary:
        "Research and product packaging: brief, competitor analysis, prioritised feature list, work plan and budget.",
      tasks: [
        "Prepared the brief and competitor analysis.",
        "Built the feature list and prioritised requirements.",
        "Planned work, budget and resources.",
        "Produced the project charter and final client presentation.",
      ],
      results: [
        "Delivered a structured implementation plan.",
        "Aligned the client and the team on a shared product vision.",
      ],
      tools: ["Miro", "Google Sheets", "Google Docs", "CustDev"],
      accent: "violet",
    },
  ],
  skills: [
    {
      title: "Management",
      items: ["Project management", "Agile", "Scrum", "Kanban", "Waterfall", "SDLC", "Risk management", "CustDev", "MVP", "User Story Mapping"],
    },
    {
      title: "Analysis & docs",
      items: ["Requirements analysis", "BRD", "Technical specs", "UML", "BPMN", "FlowChart", "User Story", "Use case", "Test Design", "Test case", "SQL"],
    },
    {
      title: "Tools",
      items: ["Jira", "Confluence", "Trello", "Notion", "Miro", "Figma", "GanttPro", "Postman", "Swagger", "Slack", "Google Workspace"],
    },
    {
      title: "Development",
      items: ["Next.js", "TypeScript", "TanStack", "Zod", "Tailwind CSS", "Node.js", "Zustand", "Git"],
    },
  ],
  aiTools: ["ChatGPT", "Claude", "Cursor", "YandexGPT", "Alisa AI"],
  courses: [{ year: "2026", title: "Project Manager", org: "Yandex Practicum" }],
  certificates: [
    { year: "2026", title: "Project Manager", org: "Yandex Practicum" },
    { year: "2024", title: "Node.js", org: "Certificate" },
    { year: "2024", title: "Zustand", org: "Certificate" },
    { year: "2024", title: "Git fundamentals", org: "Certificate" },
  ],
  languages: [
    { name: "Uzbek", level: "Native", value: 1 },
    { name: "Russian", level: "B2", value: 0.75 },
    { name: "English", level: "B2", value: 0.75 },
  ],
  education: "Secondary education",
};
